/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CruizeInterface extends ethers.utils.Interface {
  functions: {
    "borrowRatio()": FunctionFragment;
    "changeBorrowRatio(uint256)": FunctionFragment;
    "crContract()": FunctionFragment;
    "createToken(string,string,address,address,uint8)": FunctionFragment;
    "cruize_wallet()": FunctionFragment;
    "deposit(uint256,address)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "lpTokens(address)": FunctionFragment;
    "oracles(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "priceFloor()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "repay(uint256)": FunctionFragment;
    "setPriceFloor(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "borrowRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeBorrowRatio",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "crContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cruize_wallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "lpTokens", values: [string]): string;
  encodeFunctionData(functionFragment: "oracles", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceFloor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "repay", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "setPriceFloor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "borrowRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeBorrowRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "crContract", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cruize_wallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFloor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AddAsset(address,address)": EventFragment;
    "BorrowRatioChanged(uint256)": EventFragment;
    "CreateToken(address,string,string,uint8)": EventFragment;
    "DepositEvent(address,uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "WithdrawEvent(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddAsset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BorrowRatioChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawEvent"): EventFragment;
}

export type AddAssetEvent = TypedEvent<
  [string, string] & { _asset: string; _oracle: string }
>;

export type BorrowRatioChangedEvent = TypedEvent<
  [BigNumber] & { _ratio: BigNumber }
>;

export type CreateTokenEvent = TypedEvent<
  [string, string, string, number] & {
    _tokenAddress: string;
    _tokenName: string;
    _tokenSymbol: string;
    _decimal: number;
  }
>;

export type DepositEventEvent = TypedEvent<
  [string, BigNumber] & { _account: string; _amount: BigNumber }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type WithdrawEventEvent = TypedEvent<
  [string, string, BigNumber] & {
    _asset: string;
    _account: string;
    _amount: BigNumber;
  }
>;

export class Cruize extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CruizeInterface;

  functions: {
    borrowRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    changeBorrowRatio(
      ratio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    crContract(overrides?: CallOverrides): Promise<[string]>;

    createToken(
      name: string,
      symbol: string,
      reserve: string,
      tokenOracle: string,
      decimal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cruize_wallet(overrides?: CallOverrides): Promise<[string]>;

    deposit(
      amount: BigNumberish,
      reserve: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _cruize_wallet: string,
      _crContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lpTokens(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    oracles(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    priceFloor(overrides?: CallOverrides): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    repay(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPriceFloor(
      _floor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      amount: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  borrowRatio(overrides?: CallOverrides): Promise<BigNumber>;

  changeBorrowRatio(
    ratio: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  crContract(overrides?: CallOverrides): Promise<string>;

  createToken(
    name: string,
    symbol: string,
    reserve: string,
    tokenOracle: string,
    decimal: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cruize_wallet(overrides?: CallOverrides): Promise<string>;

  deposit(
    amount: BigNumberish,
    reserve: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _cruize_wallet: string,
    _crContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lpTokens(arg0: string, overrides?: CallOverrides): Promise<string>;

  oracles(arg0: string, overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  priceFloor(overrides?: CallOverrides): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  repay(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPriceFloor(
    _floor: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    amount: BigNumberish,
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    borrowRatio(overrides?: CallOverrides): Promise<BigNumber>;

    changeBorrowRatio(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    crContract(overrides?: CallOverrides): Promise<string>;

    createToken(
      name: string,
      symbol: string,
      reserve: string,
      tokenOracle: string,
      decimal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cruize_wallet(overrides?: CallOverrides): Promise<string>;

    deposit(
      amount: BigNumberish,
      reserve: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      _cruize_wallet: string,
      _crContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    lpTokens(arg0: string, overrides?: CallOverrides): Promise<string>;

    oracles(arg0: string, overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    priceFloor(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    repay(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setPriceFloor(
      _floor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      amount: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AddAsset(address,address)"(
      _asset?: string | null,
      _oracle?: null
    ): TypedEventFilter<[string, string], { _asset: string; _oracle: string }>;

    AddAsset(
      _asset?: string | null,
      _oracle?: null
    ): TypedEventFilter<[string, string], { _asset: string; _oracle: string }>;

    "BorrowRatioChanged(uint256)"(
      _ratio?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _ratio: BigNumber }>;

    BorrowRatioChanged(
      _ratio?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _ratio: BigNumber }>;

    "CreateToken(address,string,string,uint8)"(
      _tokenAddress?: string | null,
      _tokenName?: null,
      _tokenSymbol?: null,
      _decimal?: null
    ): TypedEventFilter<
      [string, string, string, number],
      {
        _tokenAddress: string;
        _tokenName: string;
        _tokenSymbol: string;
        _decimal: number;
      }
    >;

    CreateToken(
      _tokenAddress?: string | null,
      _tokenName?: null,
      _tokenSymbol?: null,
      _decimal?: null
    ): TypedEventFilter<
      [string, string, string, number],
      {
        _tokenAddress: string;
        _tokenName: string;
        _tokenSymbol: string;
        _decimal: number;
      }
    >;

    "DepositEvent(address,uint256)"(
      _account?: string | null,
      _amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _account: string; _amount: BigNumber }
    >;

    DepositEvent(
      _account?: string | null,
      _amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _account: string; _amount: BigNumber }
    >;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "WithdrawEvent(address,address,uint256)"(
      _asset?: string | null,
      _account?: string | null,
      _amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _asset: string; _account: string; _amount: BigNumber }
    >;

    WithdrawEvent(
      _asset?: string | null,
      _account?: string | null,
      _amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _asset: string; _account: string; _amount: BigNumber }
    >;
  };

  estimateGas: {
    borrowRatio(overrides?: CallOverrides): Promise<BigNumber>;

    changeBorrowRatio(
      ratio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    crContract(overrides?: CallOverrides): Promise<BigNumber>;

    createToken(
      name: string,
      symbol: string,
      reserve: string,
      tokenOracle: string,
      decimal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cruize_wallet(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      amount: BigNumberish,
      reserve: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      _cruize_wallet: string,
      _crContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lpTokens(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    oracles(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    priceFloor(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    repay(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPriceFloor(
      _floor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      amount: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    borrowRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeBorrowRatio(
      ratio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    crContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createToken(
      name: string,
      symbol: string,
      reserve: string,
      tokenOracle: string,
      decimal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cruize_wallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      amount: BigNumberish,
      reserve: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _cruize_wallet: string,
      _crContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lpTokens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracles(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceFloor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    repay(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPriceFloor(
      _floor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      amount: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
