/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ErrorsInterface extends ethers.utils.Interface {
  functions: {
    "ASSET_NOT_ALLOWED()": FunctionFragment;
    "BORROWING_ERROR()": FunctionFragment;
    "BORROW_NOT_CHANGED()": FunctionFragment;
    "ZERO_AMOUNT()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ASSET_NOT_ALLOWED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BORROWING_ERROR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BORROW_NOT_CHANGED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ZERO_AMOUNT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ASSET_NOT_ALLOWED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BORROWING_ERROR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BORROW_NOT_CHANGED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ZERO_AMOUNT",
    data: BytesLike
  ): Result;

  events: {};
}

export class Errors extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ErrorsInterface;

  functions: {
    ASSET_NOT_ALLOWED(overrides?: CallOverrides): Promise<[string]>;

    BORROWING_ERROR(overrides?: CallOverrides): Promise<[string]>;

    BORROW_NOT_CHANGED(overrides?: CallOverrides): Promise<[string]>;

    ZERO_AMOUNT(overrides?: CallOverrides): Promise<[string]>;
  };

  ASSET_NOT_ALLOWED(overrides?: CallOverrides): Promise<string>;

  BORROWING_ERROR(overrides?: CallOverrides): Promise<string>;

  BORROW_NOT_CHANGED(overrides?: CallOverrides): Promise<string>;

  ZERO_AMOUNT(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ASSET_NOT_ALLOWED(overrides?: CallOverrides): Promise<string>;

    BORROWING_ERROR(overrides?: CallOverrides): Promise<string>;

    BORROW_NOT_CHANGED(overrides?: CallOverrides): Promise<string>;

    ZERO_AMOUNT(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ASSET_NOT_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    BORROWING_ERROR(overrides?: CallOverrides): Promise<BigNumber>;

    BORROW_NOT_CHANGED(overrides?: CallOverrides): Promise<BigNumber>;

    ZERO_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ASSET_NOT_ALLOWED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BORROWING_ERROR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BORROW_NOT_CHANGED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ZERO_AMOUNT(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
